.pragma library

/* Margins */
var INDENT_DEFAULT = 10;

/* Main */
var APP_MINIMUM_WIDTH = 640;
var APP_MINIMUM_HEIGHT = 480;
var BACKGOUND_COLOR = "#C2BBA9";


/* Board */
var BOARD_SIZE = 8;
var CELL_LIGHT_COLOR = "#E5CB7E";
var CELL_DARK_COLOR = "#95582C";
var CELL_CHOOSE_COLOR = "blue";
var BOARD_BORDER_COLOR = "#6D3E12";
var BOARD_BORDER_WIDTH = 1;


/* Buttons */
var BUTTON_RADIUS = 4;
var BUTTON_COLOR = "#020001";
var BUTTON_PRESSED_COLOR = "#766F65";
var BUTTON_TEXT_COLOR = "#FFFFFF";
var BUTTON_FONT_FAMILY = "Helvetica";
var BUTTON_FONT_SIZE = 20;
